'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';

const slides = [
  { title: 'Champions who move us forward', desc: 'Celebrating IndianOil Sportstar and World Archery Para Champion Sheetal Devi, whose journey inspires possibility.', img: '/assets/Banner-20909202611eee.jpeg', alt: 'IndianOil Sportstar and para archery champion Sheetal Devi', cta: 'Explore the story' },
  { title: 'Integrated Annual Report 2025–26', desc: 'Find IndianOil’s annual reporting and corporate information in one place.', img: '/assets/banner07082026.jpeg', alt: 'IndianOil annual report campaign', cta: 'View investor information' },
  { title: 'A winning spirit, shared', desc: 'Celebrating IOCians Satwiksairaj Rankireddy and Chirag Shetty.', img: '/assets/Banner-2jhbdbvfudgbasas.jpeg', alt: 'IndianOil athletes Satwiksairaj Rankireddy and Chirag Shetty', cta: 'Explore the story' },
];
const updates = [
  ['Engagement of Apprentices at Mathura Refinery', 'recruitment'],
  ['Engagement of Apprentices at Bongaigaon Refinery 2026–27', 'recruitment'],
  ['Research Associate positions in a DBT-sanctioned research project', 'recruitment'],
  ['EOI for engagement of LA staff at Chennai and Bengaluru', 'notices'],
  ['Recruitment of Executives through Computer Based Test (CBT) – 2026', 'recruitment'],
  ['Engagement of Apprentices at Paradip Refinery – 2026', 'recruitment'],
  ['Scam Alert', 'notices'],
];
const services = [['⌁','Motorist','Fuel, mobility and service information.'],['⌂','Households','LPG information and assistance.'],['▤','Business Partners','Business, supplier and tender information.'],['◎','Careers','Recruitment and apprenticeship notices.'],['₹','Investors','Reports and investor information.'],['▧','Media','News, announcements and resources.']];
const businesses = [['◉','Refining','Explore refining operations and information.'],['⇢','Pipelines','Learn about pipeline transportation.'],['⌕','Research & Development','Discover research and innovation.'],['◈','Marketing','Products, services and customer channels.'],['◇','Petrochemicals','IndianOil’s petrochemicals business.'],['≋','Natural Gas','Natural gas business information.'],['⌖','Exploration & Production','Explore E&P business information.'],['▱','Explosives','Information about explosives operations.'],['❄','Cryogenics','Explore cryogenic products and capabilities.']];

function Header() {
  const [open, setOpen] = useState(false);
  return <><div className="utility"><div className="wrap utilityInner"><div className="utilLeft"><a href="#">हिन्दी</a><a href="#accessibility">Accessibility</a><a href="#">◖ Voice search</a><a href="#contact">Contact &amp; help</a></div><div className="utilRight"><a href="#contact">Help &amp; contact</a><a className="emergency" href="tel:1906">LPG Emergency · 1906</a></div></div></div><header className="masthead"><div className="wrap mastInner"><a className="logo" href="#top" aria-label="IndianOil home"><img src="/assets/logo.gif" alt="IndianOil"/><span><strong>IndianOil</strong><small>The Energy of India</small></span></a><form className="search" role="search" onSubmit={e=>{e.preventDefault(); document.getElementById('search-note').hidden=false}}><input aria-label="Search IndianOil" placeholder="Search services, notices, information"/><button aria-label="Submit search">⌕</button></form><button className="menuToggle" aria-expanded={open} aria-controls="mainnav" onClick={()=>setOpen(!open)}>☰ Menu</button></div><nav id="mainnav" className={`nav ${open?'open':''}`} aria-label="Main navigation"><div className="wrap navInner"><div className="navmenu"><button>About IndianOil ▾</button><div className="drop"><a href="#about">Overview</a><a href="#about">Leadership &amp; organisation</a><a href="#subsidiaries">Overseas subsidiaries</a></div></div><div className="navmenu"><button>Services ▾</button><div className="drop"><a href="#services">Motorist</a><a href="#services">Households</a><a href="#services">Business Partners</a></div></div><div className="navmenu"><button>Businesses ▾</button><div className="drop"><a href="#business">Refining &amp; Pipelines</a><a href="#business">Research &amp; Development</a><a href="#business">Marketing &amp; Petrochemicals</a><a href="#business">Natural Gas, E&amp;P</a><a href="#business">Explosives &amp; Cryogenics</a></div></div><a href="#people">People &amp; Society</a><a href="#sustainability">Environment</a><a href="#updates">Media</a><a href="#investors">Investors</a></div></nav></header></>;
}

export default function Home() {
  const [current,setCurrent]=useState(0), [paused,setPaused]=useState(false), [filter,setFilter]=useState('all'), [detailOpen,setDetailOpen]=useState(false), [businessDetail,setBusinessDetail]=useState(null);
  useEffect(()=>{ if(paused)return; const timer=setInterval(()=>setCurrent(n=>(n+1)%slides.length),8000); return ()=>clearInterval(timer); },[paused]);
  const s=slides[current];
  return <><Header/><main id="top"><p id="search-note" hidden className="searchNote wrap">Search destinations need to be connected to the approved site search.</p>
    <section className="hero" aria-label="Featured announcement"><div className="wrap heroGrid"><div className="heroCopy"><div className="eyebrow">Energy for every journey</div><h1>{s.title}</h1><p>{s.desc}</p><button className="btn primary" onClick={()=>setDetailOpen(true)}>{s.cta} <span>?</span></button><div className="heroControls" aria-label="Featured story controls">{slides.map((item,i)=><button key={item.title} className={`dot ${i===current?'active':''}`} aria-label={`Show ${item.title}`} onClick={()=>setCurrent(i)}/>)}<button className="controlBtn" aria-label={paused?'Resume rotation':'Pause rotation'} onClick={()=>setPaused(!paused)}>{paused?'▶':'Ⅱ'}</button><span>Featured stories</span></div></div><button className="heroArt" onClick={()=>setDetailOpen(true)} aria-label={`View details: ${s.title}`}><Image src={s.img} alt={s.alt} fill priority sizes="(max-width:680px) 100vw, 600px" style={{objectFit:'contain'}}/></button></div></section>
    <section className="noticeStrip"><div className="wrap noticeInner"><span className="noticePill">Notice</span><a href="#updates">Scam Alert — verify communications through official IndianOil channels.</a><a className="all" href="#updates">All announcements →</a></div></section>
    <section id="services" className="section"><div className="wrap"><div className="sectionHeading"><div><div className="eyebrow blue">Here to help</div><h2>How can we help you?</h2><p>Find the right starting point for services, support and information.</p></div><a href="#contact" className="textLink">View all services →</a></div><div className="serviceGrid">{services.map(([icon,title,desc])=><a className="service" href="#contact" key={title}><div className="icon">{icon}</div><h3>{title}</h3><p>{desc}</p><span className="arr">↗</span></a>)}</div><p className="finePrint">Prototype links: destinations require verification before launch.</p></div></section>
    <section className="section alt" id="updates"><div className="wrap twoCol"><div className="panel"><div className="sectionHeading compact"><div><div className="eyebrow blue">From IndianOil</div><h2>Latest updates</h2></div><a href="#" className="textLink">All updates →</a></div><div className="tabs" role="tablist" aria-label="Filter updates">{[['all','All'],['recruitment','Recruitment'],['notices','Notices'],['news','News']].map(([id,label])=><button key={id} role="tab" aria-selected={filter===id} className={`tab ${filter===id?'active':''}`} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="updates">{updates.filter(([,type])=>filter==='all'||filter===type).map(([title,type])=><a className="update" href="#" key={title}><strong>{title}</strong><span className="type">{type==='recruitment'?'Recruitment':'Notice'}</span></a>)}</div><p className="finePrint">Dates and destinations omitted pending verification.</p></div><aside className="investCard" id="investors"><div className="eyebrow">For shareholders &amp; analysts</div><h2>Investor information</h2><p>Access IndianOil’s investor resources and corporate disclosures.</p><div className="miniLinks"><a href="#">Integrated Annual Report 2025–26 <span>↗</span></a><a href="#">Saksham Niveshak <span>↗</span></a><a href="#">Special window for re-lodgement of transfer requests <span>↗</span></a></div><p className="finePrint">Titles supplied for review; confirm publication status and approved destinations.</p></aside></div></section>
    <section className="section" id="business"><div className="wrap"><div className="sectionHeading"><div><div className="eyebrow blue">What we do</div><h2>Businesses &amp; capabilities</h2><p>Explore IndianOil’s business areas and capabilities.</p></div><a href="#" className="textLink">About IndianOil →</a></div><div className="businessGrid">{businesses.map(([icon,title,desc])=><button className="business" key={title} onClick={()=>setBusinessDetail({icon,title,desc})}><div className="icon">{icon}</div><div><h3>{title}</h3><p>{desc}</p><span className="businessMore">View details <span aria-hidden="true">↗</span></span></div></button>)}</div><p className="finePrint">Descriptions are draft wayfinding copy and require corporate review.</p></div></section>
    <section className="section alt" id="sustainability"><div className="wrap"><div className="sectionHeading"><div><div className="eyebrow blue">Responsibility &amp; progress</div><h2>Energy for a changing future</h2><p>Explore IndianOil’s environment, safety and community information.</p></div></div><div className="sustainGrid"><div className="sustainFeature"><div className="eyebrow">Our green agenda</div><h2>Moving forward with care</h2><p>Read about IndianOil’s Green Agenda, health, safety and environment work, and green fuel alternatives.</p><a href="#" className="btn primary">Explore sustainability ↗</a></div><div className="sustainLinks" id="people">{['IndianOil’s Green Agenda','Health, Safety & Environment','Green Fuel Alternatives','Society, sports & para-sports'].map(t=><a href="#" key={t}>{t}<span>↗</span></a>)}</div></div><p className="finePrint">No performance claims are made here. Link destinations and current approved content require review.</p></div></section>
    <section className="section" id="subsidiaries"><div className="wrap"><div className="sectionHeading"><div><div className="eyebrow blue">Beyond India</div><h2>International presence</h2><p>Meet IndianOil’s overseas businesses.</p></div></div><div className="subsidiaries"><article className="sub"><h3>Lanka IOC PLC</h3><p>Supplied reference describes IndianOil’s subsidiary in Sri Lanka and notes its ranking among leading companies on the island.</p><span className="verify">Claim and ranking require current verification</span></article><article className="sub"><h3>IndianOil (Mauritius) Ltd.</h3><p>Supplied reference describes the company as the third-largest petroleum company in Mauritius.</p><span className="verify">Claim requires current verification</span></article><article className="sub"><h3>IOC Middle East FZE</h3><p>Supplied reference describes its role in business expansion across the Middle East, Africa and CIS countries.</p><span className="verify">Description requires current verification</span></article></div></div></section>
    <section className="contactBand" id="contact"><div className="wrap contactInner"><div><h2>Need LPG assistance?</h2><p>Support numbers supplied for the homepage concept.</p></div><div className="phoneList"><a href="tel:18002333555"><small>Toll Free Number</small>1800-2333-555</a><a href="tel:18605991111"><small>Commercial LPG Helpline</small>1860-5991-111</a><a href="tel:1906"><small>LPG Emergency</small>1906</a></div></div></section>
  </main>{businessDetail&&<div className="storyOverlay" onMouseDown={e=>{if(e.target===e.currentTarget)setBusinessDetail(null)}}><section className="businessDialog" role="dialog" aria-modal="true" aria-labelledby="business-title"><button className="storyClose" onClick={()=>setBusinessDetail(null)} aria-label="Close details">×</button><div className="businessDialogIcon">{businessDetail.icon}</div><div className="eyebrow blue">IndianOil capability</div><h2 id="business-title">{businessDetail.title}</h2><p>{businessDetail.desc}</p><p>Explore this business area to learn how it supports IndianOil’s integrated energy operations and serves customers across India.</p><button className="btn primary" onClick={()=>setBusinessDetail(null)}>Close details</button></section></div>}{detailOpen&&<div className="storyOverlay" onMouseDown={e=>{if(e.target===e.currentTarget)setDetailOpen(false)}}><section className="storyDialog" role="dialog" aria-modal="true" aria-labelledby="story-title"><button className="storyClose" onClick={()=>setDetailOpen(false)} aria-label="Close details">�</button><div className="storyImage"><Image src={s.img} alt={s.alt} fill sizes="(max-width:680px) 100vw, 460px" style={{objectFit:'contain'}}/></div><div className="storyBody"><div className="eyebrow blue">Featured story � IndianOil</div><h2 id="story-title">{s.title}</h2><p>{s.desc}</p><p>Discover the people, ideas and progress behind this IndianOil feature.</p><button className="btn primary" onClick={()=>setDetailOpen(false)}>Back to homepage</button></div></section></div>}<footer className="footer" id="about"><div className="wrap"><div className="footerGrid"><div><a className="logo" href="#top"><img src="/assets/logo.gif" alt=""/><span><strong>IndianOil</strong><small>The Energy of India</small></span></a><p className="footerTag">Energy for every journey.</p></div><div><h3>Popular destinations</h3><a href="#services">Motorist</a><a href="#services">Households</a><a href="#services">Business Partners</a><a href="#updates">Careers &amp; apprenticeships</a></div><div><h3>Businesses &amp; corporate</h3><a href="#business">Our businesses</a><a href="#sustainability">Environment &amp; society</a><a href="#subsidiaries">Overseas subsidiaries</a><a href="#investors">Investors</a><a href="#updates">Media</a></div><div><h3>Policies &amp; help</h3><a href="#">Site Map</a><a href="#">Terms of Use</a><a href="#">Data Privacy Policy</a><a href="#">Hyperlinking Policy</a><a href="#">Swachh Bharat</a><a href="#">india.gov</a></div></div><div className="footBottom"><span>© Indian Oil Corporation Ltd. · Official name and brand identity retained.</span><span>Last updated: generated by publication system · Confirm policy names and links before launch.</span></div></div></footer><div className="draft">HOMEPAGE CONCEPT · DRAFT CONTENT · LINKS UNVERIFIED</div></>;
}
